[package]
name = "batpu_emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
arrayvec = "0.7.4"
bitvec = "1.0.1"
clap = { version = "4.5.11", features = ["derive"] }
crossterm = "0.27.0"
libloading = "0.8.5"
once_cell = "1.19.0"
rand = "0.8.5"
